### ISSUE TITLE
A introduction on synthetic dataset

### ISSUE THREAD

**Issue by Liumucan** [zeshanmh/ief#1]
Hi, Hussain! Thanks for your great research. I'm wondering could you please provide a introduction about how to use synthetic dataset to run your model ?

**Comment by zeshanmh** [comment]
hi! yes, i'm working on a branch (refactor), where I've created a notebook that loads in the synthetic data and a model trained on the synthetic data. 

to train a model on synthetic data, you can use: 

python main_trainer.py --model_name ssm --dataset synthetic --ttype attn_transition --reg_type l1 --reg_all all --C 0.01 --dim_stochastic 48 --fold 1 --max_epochs 15000 --ckpt_path /afs/csail.mit.edu/u/z/zeshanmh/research/ief/ief_core/checkpoints/ 

people have also had some issues with dependencies, so i'm uploading a poetry config that'll make creating the environment easier.

**Comment by Liumucan** [comment]
Thank you very much !
